//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ARMEntities : DbContext
    {
        public ARMEntities()
            : base("name=ARMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Charge> Charges { get; set; }
        public virtual DbSet<ConsumptionCharge> ConsumptionCharges { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<staffMember> staffMembers { get; set; }
    
        public virtual int addition()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addition");
        }
    
        public virtual int addition2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addition2");
        }
    
        public virtual int addition3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addition3");
        }
    }
}
